name: Build and Publish
on:
  - push
  - pull_request
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.head_commit.message, 'bump:') }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm install
      - run: npm run build
      - name: Configure NPM publish token
        run: npm config set //registry.npmjs.org/:_authToken $NODE_AUTH_TOKEN
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm publish
